package com.ssm.entity;

import java.util.Date;

public class tblResident {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_resident.sid
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_resident.name
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_resident.age
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_resident.area
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_resident.birth_time
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    private Date birthTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_resident.pass_word
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_resident.user_name
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_resident.sid
     *
     * @return the value of tbl_resident.sid
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_resident.sid
     *
     * @param sid the value for tbl_resident.sid
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_resident.name
     *
     * @return the value of tbl_resident.name
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_resident.name
     *
     * @param name the value for tbl_resident.name
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_resident.age
     *
     * @return the value of tbl_resident.age
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_resident.age
     *
     * @param age the value for tbl_resident.age
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_resident.area
     *
     * @return the value of tbl_resident.area
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_resident.area
     *
     * @param area the value for tbl_resident.area
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_resident.birth_time
     *
     * @return the value of tbl_resident.birth_time
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public Date getBirthTime() {
        return birthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_resident.birth_time
     *
     * @param birthTime the value for tbl_resident.birth_time
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public void setBirthTime(Date birthTime) {
        this.birthTime = birthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_resident.pass_word
     *
     * @return the value of tbl_resident.pass_word
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_resident.pass_word
     *
     * @param passWord the value for tbl_resident.pass_word
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_resident.user_name
     *
     * @return the value of tbl_resident.user_name
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_resident.user_name
     *
     * @param userName the value for tbl_resident.user_name
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}