package com.ssm.dao;

import com.ssm.entity.tblResident;
import java.util.List;

public interface tblResidentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_resident
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_resident
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    int insert(tblResident record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_resident
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    tblResident selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_resident
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    List<tblResident> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_resident
     *
     * @mbggenerated Fri Dec 11 21:36:22 CST 2020
     */
    int updateByPrimaryKey(tblResident record);
    
    /**
     * 自定义方法
     */
   	 List<tblResident> findList(int start,int size);

	int findBycount();
   		
}